spring:
  application:
    name: consumer-with-vt-thread
  threads:
    virtual:
      enabled: true

server:
  port: 8080

consumer:
  hostName: http://localhost:8081
  path: /api/v1/sleep/

demo:
  url: https://jsonplaceholder.typicode.com
  summary: https://apidojo-yahoo-finance-v1.p.rapidapi.com
  keyFileName: classpath:key.txt

management:
  endpoints:
    web:
      exposure:
        include: "*"