spring:
  application:
    name: consumer-with-vt-thread
  threads:
    virtual:
      enabled: false

server:
  port: 8080
  servlet:
    context-path: /consumer


consumer:
  hostName: http://localhost:8081
  contextPath: /producer
  path: /api/v1/sleep/
